name: portabase-dev

services:
  db:
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U devuser -d devdb" ]
      interval: 10s
      timeout: 5s
      retries: 5

  tusd:
    image: tusproject/tusd:v2.8.0
    ports:
      - "1080:8080"
    command: >
      -upload-dir /data/uploads/tmp
      -hooks-http http://localhost:8887/api/tus/hooks
      -max-size 21474836480
      -base-path /tus/files/
    extra_hosts:
      - "localhost:host-gateway"
    volumes:
      - ./private/uploads/tmp:/data/uploads/tmp
    user: "1000:1000"

  mailpit:
    image: axllent/mailpit:latest
    container_name: portabase-mailpit-dev
    hostname: mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  postgres-data:
